dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
services:
- postgresql
before_script:
- psql -c 'create database frameworkeventstore;' -U postgres
- psql -c "CREATE USER framework WITH PASSWORD 'framework';" -U postgres
addons:
  postgresql: '9.5'
  sonarcloud:
    organization: cjscommonplatform
    token:
      secure: Lb5gA3NBMFf8VnTNjf2KAcy5S0+cvSSz2qaiN0diHSIi205nT12Foom27bCQnn2+Kxfzljn3hdIA3GUEipwh/UbZQHCdFl3mROMm28psWO7nZvNz82vwYlrpGiXzrkn5YAL9QRFbnzrCZwIZSGinQojaZ72H3/FwmSYlBKE++ito2HPPdD8wrLYVUBKp06u683NQQU4koLSU50pFgkbIcFkeUNwrVT8t69tW2+abEgzfpa5o6ExcPATcxKYJ8fPx/C/x9XjcNVYho5nAJ7KRy0PkS3MEAnjOIBwVHZrXb2qjeoJ5T9AJfuXwaTCyMFA/e+gyGn28CsQkzHohE4VZUovn5MdU9Hkzz9xOwU7JS8837JNAlPy2+U71oemGXwdB8D4LnuxkghBw9JukFq1EqqeLv0CQWU/iBAYYPIHIdjFUTcolPM14VhCQfj0XPIR7oyIDsOivjcK0ULSY6pInGszFgbex0ApVWD6t7l3yoFmbZMfdviAmuzUEtwwwIyffq76at64iH9rz1VbcUesF6ls+/02/Umvx1azReQqQ+/ciRCK6I/NtnfGzDvYlVtQA6+HigRBivRLbjrv9iaGHG+54aP1cne2n1QJUkke58yLjLWvhfcXIIB2nsrTqEyJx1qfMdPUlKFqrHZQJu/pp2cxY8uwkLe2Eur7jRNofIE8=
    github_token:
      secure: cEzLKBpESOAsBZTzfnxFW0vGt5cmiys0eLX1VdKWarIBluW4tBsxuCsZAjJq1Gqvhfc+bfYNPr6cB1hueK/sQ6ktpmXjM9NtihPbkLKulBi917449osOlumUeRVVQds8hm46R4/p67s8qocyHNh3oHn9caBFOisFe8OrFL3lgGW7ymkWpGeAFlY1yHMdns2o/ISdOoQ8R7vJX4Qi9XLLi7IaKlY4vSBJB17rThqQxVhAe+z9rE7gZGcXjZhRBMZcUKXJNDUTLvnfjdJBF/uNHrpT3gEJJnnlelxv0ROaWeJX7UXGJ9cjdDgEpKObejuGNCgmHRqT5rgpOQjNCU2vvNJoNFEQUR0UszIq3W2BPX5y+jOYfNw2QkihQRWA+UxkMy48/yfkjEqiRA1YgvrLZBz4oaCeeaxzcAeZjVoQaYfNfK1MUzka0yoZ3tZT7zaiJmcAxW5Mn0HYfL2KgHgz18TT4S9lH5aRG27lvUAwguFS77f4+TtpOk3qhkm3M7rqP8gmYKRW2ioRLd8ZGYcyTg/QSrJSu6RIrloj3KmAb7kIekZHXPZ6fp8jMIYafDZjRFM7mkJpEBBCtkKZL7xeYgUbvhAhWEa9fb3ifUjGTMG4oIDZsveFgfhB8CMB5LzX0WlNuxEChmTcM+dYJzl+WL21Qesb6ULowW1LvsG1CUc=
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
- ln -sfT ${PWD}/target/travis-settings/mvnw mvnw
- ln -sft ${PWD} ${PWD}/target/travis-settings/.mvn
install: "${PWD}/target/travis-settings/java/install.sh -e -q -DexcludeGroupIds=uk.gov.justice.service,uk.gov.justice.services"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report sonar:sonar"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications: 
env:
  global:
  - PGPORT=5432
  - secure: gQ6wQLYtzo/Cs+ukVM9bfUsbYrFI8vSW1jDgCZYCh5ANJo4GajxIiUL0pn1ogMG/40Aha1ZECIgcDQzd1sP+ehXuC5X4K9gySa/4x+Qov0tGD2Txj6qrwYzEAGjtuRAGM3kAWuezI2bRiMFN72ob/BHHS9nWn3yA9rfu6VQ3rC1z5EPBrpTkzic+us0YIODLWO4ZjlVA/f7HxN1Qot+1MvcKUod7YrLU4Rp7MTaoqdl+d/DqmXp5u3c5QikEKnYJ0s7bKc1y1R3R4xsDEENr1o+Dgpd8CPcfFLoXzhJ9txfyUX4DX8PaWhGBuJh8SmwRdKIGpNW9bWWaCX2ATXD9RG92j8edAkk3kCcltdeNIKjr0+Oi44pXG5OS91g5m+EOxFooVzg1mFENZAgjTGeHztwKZSFg7zgBbuovBYRqOPl6AxRO8oLP/6FxdKm2UOzWwZWtnoFYocoXrDVqSTaByY+iD1fGfIwTy9QY1epvUeAHsyJ/bz+SJQmTrGw80/eeEJrxbzZCM8GQ05tPvZY2qhhNP7UKcrxXk2eBtefcXyjDKTk7dTLhOhfoWdkPOryKtVh7IWVGGI7rrRqV3m7/xz2HbvRcGZJxCu8xyNZDobZhASkFpUwb1rZOyaJezWxJ/o/0b2VulfK5DRN0bU0QF0XItifUx4PKz94bMdzkNNE=
  - secure: OXBT6QVGUQLtWpP9g+g6X7u9pVDysosvVwg9lTB2hpzEVb6h4DVigZ2fFMokmfTV1jc+vE14WRYlA6SDhk+ZVZ/uFBoDq5FJdVELWYVmLg9xh+/mfwoh+0+1QxeZicUhCDCiibcj9uSr/9CDNUiLSwUvlTGYkXHRYLEHfuvHBMVfPOMldJbJsPAcWBId4K9EDU8rXrCq5RJA0fICSGWunAInaw8jC32ci31u0bilnHzBdpDfCuAY+7as9FAt7zTQkbj2gJXd0FpYSOhdNpUMT8naLfsIF5Nl3v4MzlswK4vk5rfRx9tNpIRiJ9m2Qx4aJHfNAZMV86QP1PTRvWxHKHOY+i1keYAirt69T0jZtn+c2my/7GfU36PaNQZWoXtkZ2MX4CtIUivH3JwN33f2Qb5yyUTfohXC6h6gt+RctXBiOcrHZcGTyHZFZKVrM9rLxjZW1Lg+hn3M/MEu9C1jpUBdooVGP3hebWDGf6ZCEBL1C5WUn21VoN3vdyXi5nN9Hawh1es7XvzJf8NMt3OfRN1h+WNBSOOWOh0sin7myGxRt6T+7o3N5uEtpTRtTVb+HVTtnVQZi6RaBKVCsfUTB7/ctLzeVSXyhSi7prwvTxaKjGLHGKVO1uKMniEYPoyro65hBRWdW9D+hZjyW/C88cXzYOP1SHnGLIFVY7hD05Q=
